### ISSUE TITLE
Book vision and dental care

### ISSUE THREAD

**Issue by ifyouseewendy** [ifyouseewendy/verbose-disco#36]
Vision care for both

<img width="719" alt="Screen Shot 2019-12-03 at 16 44 24" src="https://user-images.githubusercontent.com/1019171/70092405-40b09180-15ec-11ea-8932-1ab9a718b016.png">

Dental care for both

![image](https://user-images.githubusercontent.com/1019171/70092439-4f974400-15ec-11ea-8c82-078ddb6367e3.png)

**Comment by yuanting0505** [comment]
@ifyouseewendy 问一下David
